### PR TITLE
CLI code base

### PR DESCRIPTION
**Pull request by Harsh14901**
Tasks Completed
- Parse input files
- Extract audio async from all the files
- Get track status from VLC and issue commands to VLC
- Code to communicate with the server has been created however it has not yet been integrated in `main.py` since server is not complete. This was tested using a dummy server and dummy functions have been created in `main.py` to fullfil the need.

TODO
-  Some code in `server_comm.py` will have to be changed as per the requirements of the server side code.
- Functionality for changing items in playlists and our code needs to respond to that.
- File upload should be done in the background and only when it is complete we should start the playback

### CODE REVIEW

**Comment by ankurshaswat** [comment]
I have put in PR to your fork improving some code fixes.
Please pay heed to those next time by running tests locally too.
Also, parse_logs is too complex according to the check, you will have to split it into sub-functions.

**Comment by codeboy5** [comment]
Cool guys, I will check this out and merge it.

**Comment by imperfect-fourth** [comment]
@ankurshaswat are you planning to squash and merge all these commits?

**Comment by ankurshaswat** [comment]
No
Most of these look cool.
Few of them could be squashed using cli and pushed.

**Comment by imperfect-fourth** [comment]
@ankurshaswat haan i would prefer if merge commits naa ho in mein. git history ajeeb ho jaegi

**Pull request merged**
